version: "3.2"
services:
  frontend:
    restart: always
    command: npm start
    container_name: deploy-test02
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
