name: release app

on:
  push:
    branches:
      - "main" # 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest # OS 환경
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2 # 코드 check out: 프로젝트의 소스코드를 내려받는다.

      #- name: Install dependencies
      #run: npm install

      - name: Generate deployment package
        run: zip -r ${{ github.sha }}.zip . -x "*.git*" node_modules

      - name: Deploy to EB
        #uses: contability/deploy-test-beanstalk1@main
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: deploy-docker-test02
          environment_name: Deploy-docker-test02-env
          version_label: ${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-744319879458
          region: ap-southeast-2
          deployment_package: ${{ github.sha }}.zip
